export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_RESTAURANT_REVIEWS = 'UPDATE_RESTAURANT_REVIEWS';
